openapi: 3.0.0
info:
  title: User Register and Login
  description: "The user registration API creates a user account in your application. A registration request must provide a user object as a collection of key/value properties. The collection must contain a property marked as identity as well as the password property. The default identity property is name."
  version: "0.0.0"
paths:
  /Userlogin:
    post:
      summary: User Login
      description: "User Login"

      responses:
        '200':
          description: User Login report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Userlogin'

        '503':
          description: Unsuccess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - reason
      properties:
        errormessage:
          type: object
        errorcode:
          type: object

    Userlogin:
      required:
        - service
      properties:
        username:
          type: object
        password:
          type: object
        userid:
          type: object

